server:
  port: 8081

spring:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: none
  datasource:
    url: jdbc:h2:file:./db/acmebank
    driverClassName: org.h2.Driver
    username: username
    password: password
  h2:
    console:
      enabled: true
